# Book settings
# template from https://github.com/executablebooks/github-action-demo
title: Modelos y Simulación de Sistemas II
author: Profesora Maria Bernarda Salazar Sánchez -- Laboratorio por Germán E. Melo  -  Universidad de Antioquia 
logo: Images/fudea.jpg

repository:
   url: https://github.com/mariabda2/ML_2022
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

execute:
  execute_notebooks: off



